# Generated by Django 4.0.6 on 2022-07-25 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userroles',
            name='role',
            field=models.CharField(choices=[('VE', 'VENDOR'), ('CU', 'CUSTOMER')], max_length=2),
        ),
        migrations.DeleteModel(
            name='Roles',
        ),
    ]
