# Generated by Django 4.0.6 on 2022-07-25 06:19

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_useractivity'),
    ]

    operations = [
        migrations.CreateModel(
            name='Roles',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='userroles',
            name='role',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='users.roles'),
        ),
    ]
